// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","path":"/home","file":"@/pages/Home/index.tsx","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"权限演示","path":"/access","file":"@/pages/Access/index.tsx","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":" CRUD 示例","path":"/table","file":"@/pages/Table/index.tsx","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"会员登陆","path":"/user/login","file":"@/pages/User/login.tsx","parentId":"ant-design-pro-layout","id":"5"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","file":"@/.umi/plugin-layout/Layout.tsx","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "2" */'@/pages/Home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "3" */'@/pages/Access/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "4" */'@/pages/Table/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "5" */'@/pages/User/login.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "ant_design_pro_layout" */'@/.umi/plugin-layout/Layout.tsx')),
},
  };
}
