// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"Table/components/CreateForm":{"path":"Table/components/CreateForm","id":"Table/components/CreateForm","file":"Table/components/CreateForm.tsx"},"Table/components/UpdateForm":{"path":"Table/components/UpdateForm","id":"Table/components/UpdateForm","file":"Table/components/UpdateForm.tsx"},"Access/index":{"path":"Access","id":"Access/index","file":"Access/index.tsx"},"Table/index":{"path":"Table","id":"Table/index","file":"Table/index.tsx"},"Home/index":{"path":"Home","id":"Home/index","file":"Home/index.tsx"},"User/login":{"path":"User/login","id":"User/login","file":"User/login.tsx"}},
    routeComponents: {
'Table/components/CreateForm': React.lazy(() => import(/* webpackChunkName: "Table_components_CreateForm" */'../../../src/pages/Table/components/CreateForm.tsx')),
'Table/components/UpdateForm': React.lazy(() => import(/* webpackChunkName: "Table_components_UpdateForm" */'../../../src/pages/Table/components/UpdateForm.tsx')),
'Access/index': React.lazy(() => import(/* webpackChunkName: "Access_index" */'../../../src/pages/Access/index.tsx')),
'Table/index': React.lazy(() => import(/* webpackChunkName: "Table_index" */'../../../src/pages/Table/index.tsx')),
'Home/index': React.lazy(() => import(/* webpackChunkName: "Home_index" */'../../../src/pages/Home/index.tsx')),
'User/login': React.lazy(() => import(/* webpackChunkName: "User_login" */'../../../src/pages/User/login.tsx')),
},
  };
}
